# data validation configuration file

validation_operators:
  - name: expect_column_values_to_be_unique
    column: 'column1'
  - name: expect_column_values_to_be_of_type
    column: 'column2'
    type: 'int'
  - name: expect_column_values_to_match_regex
    column: 'column3'
    regex: '^[a-zA-Z]*$'

validation_expectations:
  - expectation_type: 'expect_column_values_to_be_unique'
    column: 'column1'
  - expectation_type: 'expect_column_values_to_be_of_type'
    column: 'column2'
    type: 'int'
  - expectation_type: 'expect_column_values_to_match_regex'
    column: 'column3'
    regex: '^[a-zA-Z]*$'